version: '3.2'
services:
  php-apache:
    build: .
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./project
        target: /var/www/html
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kkk111
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8080:80
    volumes:
     - /sessions
    depends_on:
     - db
